name: Deploy Demo to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'react-jigsaw/demo/**'
      - 'react-jigsaw/.github/workflows/deploy-demo.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: react-jigsaw/demo/package-lock.json

      - name: Install dependencies
        working-directory: react-jigsaw/demo
        run: npm ci

      - name: Build
        working-directory: react-jigsaw/demo
        env:
          VITE_BASE: '/${{ github.event.repository.name }}/demo/'
        run: npm run build

      - name: Prepare artifact under /demo
        run: |
          rm -rf site
          mkdir -p site/demo
          cp -R react-jigsaw/demo/dist/* site/demo/
          cp site/demo/index.html site/demo/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
